version: "3.5"
services:
  db-contosouni:
    image: mysql:8.0
    restart: always
    ports:
        - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: mydb
        MYSQL_USER: uni
        MYSQL_PASSWORD: pa$$word
        MYSQL_ROOT_PASSWORD: pa$$word
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    networks:
        - contosouni-net
  phpmyadmin-contosouni:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
        - db-contosouni:db
    ports:
        - 8401:80
    environment:
        MYSQL_USER: uni
        MYSQL_PASSWORD: pa$$word
        MYSQL_ROOT_PASSWORD: pa$$word
    networks:
        - contosouni-net

networks:
  contosouni-net:
    name: contosouni-net

